title: SmartBuyers Blog
description: Platforma B2B do dropshippingu — łączymy dostawców i sprzedawców na globalnych marketplace'ach
lang: pl_PL

# Blog settings
permalink: /blog/:year/:month/:day/:title/
show_excerpts: true

# Default layout
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: article
  - scope:
      path: ""
    values:
      layout: default
